### ISSUE TITLE
Fix accordion

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#101]
**How it works**
Accordion layout is broken on small resolutions:

![CleanShot 07 11 2024 at 12-21](https://github.com/user-attachments/assets/58ba8d47-8986-41dc-91cd-ff8b147e03d5)

**How it should work**
Header:
- [x] Row should be split in 50/50 for POSITION_NAME and STATUS_STAGE labels
- [x] Text should not ignore space occupied by chevron icon
- [x] Text should be contained in the card's header

Body:
- [x] Display button below STAGE_NAME label (when have scorecard, below scorecard text groups)
- [x] Display score_icon and "by USER on DATE" text group below scorecard template link

**Comment by amgalanbadmaev** [comment]
Also, please check what width we use for stage label in scorecards - is it in line with our regular label width in cards?

**Comment by wrmk** [comment]
@amgalanbadmaev need clarify
"Text should be contained in the card's header"
means accordion header?
because in [tabler](https://preview.tabler.io/accordion.html) example all content in the `card`
![image](https://github.com/user-attachments/assets/80e2e1e2-8e38-4f14-96a5-5f5f13a70cf0)

**Comment by wrmk** [comment]
@amgalanbadmaev please clarify
"Also, please check what width we use for stage label in scorecards - is it in line with our regular label width in cards?"

We use our label component to display stage name to the left, and all related content to the right

**Comment by amgalanbadmaev** [comment]
I meant that visually it seems like labels in scorecards are wider then ones in cards, do we use the some width param for labels and is it applied correctly for the ones in scorecards?

**Comment by wrmk** [comment]
I did not find any width styles
and fast comparing did not have wider effect

https://github.com/user-attachments/assets/26338690-0dc2-4494-a10a-567ff16a2ebb
