### ISSUE TITLE
Remove line under tab button on small breakpoints

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#174]
**Problem**
On Small and Extra small breakpoints: on Position page there is line below tab button (on Candidate page there is no line);

![CleanShot 14 11 2024 at 16-48](https://github.com/user-attachments/assets/d1a7843e-c4de-4def-b329-fceba8cff097)

**Solution**
Remove this line on Position page without breaking tabs on bigger breakpoints.

And also use a component for this button so that its height should be 32 px (currently 41px).
![image](https://github.com/user-attachments/assets/addb7c4c-70eb-40aa-a906-fa4d7f3aa741)

**Comment by ksnitsky** [comment]
Description updated
