### ISSUE TITLE
Fix selected option styles in assignee select dropdown menu

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#178]
**Problem**
In https://github.com/freeats/freeats/issues/114 we applied Tabler's styles for select's dropdown menu. But Recruiter select on Candidate and Position pages doesn't have correct style for selected option.

![CleanShot 14 11 2024 at 19-14](https://github.com/user-attachments/assets/092e3eb8-21aa-41e8-8c7a-d06a7fc68a99)

Example of correct style (Open option):

![CleanShot 14 11 2024 at 19-15](https://github.com/user-attachments/assets/ab276a4c-8485-40dc-9d8d-8121264829e7)

**Solution**
Investigate why selected option style is not applied for assigned recruiter and fix it.

**Comment by ksnitsky** [comment]
@wrmk can you take this one? You have more experience with selects

**Comment by wrmk** [comment]
took
