### ISSUE TITLE
Fix score buttons focus

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#180]
**How it works**
In Candidate's scorecard:
- if Score is set, only selected Score button is focusable via tab key
- if Score is not set, only first Score button is focusable via tab key

**How it should work**
All buttons should be focusable via tab key.

Additionally: please change color text in View mode from green/red to default tblr-body-color (#182433), since it doesn't passes color contrast accessability on certain scores (2 middle ones).

![CleanShot 15 11 2024 at 00-35](https://github.com/user-attachments/assets/4c81a079-121d-4ee7-a41b-ffcc5d7b46bf)

**Comment by ksnitsky** [comment]
Not being able to select them via tab is expected behavior for radio buttons. In the tabler example they work the same way

**Comment by ksnitsky** [comment]
If it's badly needed to be able to select them via tab, I can do something with js and regular buttons

**Comment by amgalanbadmaev** [comment]
Decided to not change to regular buttons for tab focus, since it affects our code quality.

Created separate issue for animation styles on icon: https://github.com/freeats/freeats/issues/219
