### ISSUE TITLE
Fix alignment and icon position for column tabs on Pipeline

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#181]
**Problem**
On Position page, in Pipeline tab: Tab button with columns is not left-aligned and icon is centered:

![CleanShot 15 11 2024 at 00-39](https://github.com/user-attachments/assets/30b64f75-c330-4e47-b59d-48453a86ac9f)

**Solution**
Apply same styles as in Tab buttons above (general tabs, placement status tabs) - left-align text and set chevron icon to be at the right end.

**Comment by ksnitsky** [comment]
Should the internal padding in the dropdown list be the same as the button's padding?
![image](https://github.com/user-attachments/assets/05712eb3-8ed5-4973-9864-45bca1ba073e)

**Comment by amgalanbadmaev** [comment]
Yes, let's keep it (the other 2 tabs have it I think, so no problem). Also after some recent PRs I noticed that size of the general tabs and this stage column tabs changed (became 41px height). Could you please fix it as well? If will take more than 1h please create separate issue.

![CleanShot 18 11 2024 at 10-50](https://github.com/user-attachments/assets/ba07904d-c414-4648-b7fd-ca1142491a10)

**Comment by PrinceYauj** [comment]
@amgalanbadmaev, am I right that `pipeline` dropdown should have its height changed from 41px as well, not only `Sourced`?
![image](https://github.com/user-attachments/assets/8e834559-7e9a-4fb4-b928-eca82facade3)

**Comment by ksnitsky** [comment]
> @amgalanbadmaev, am I right that `pipeline` dropdown button should have its height changed from 41px as well, not only `Sourced`? ![image](https://private-user-images.githubusercontent.com/64950366/387144832-8e834559-7e9a-4fb4-b928-eca82facade3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjI1MTMsIm5iZiI6MTczMTkyMjIxMywicGF0aCI6Ii82NDk1MDM2Ni8zODcxNDQ4MzItOGU4MzQ1NTktN2U5YS00ZmI0LWI5MjgtZWNhODJmYWNhZGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA5MzAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNGYzNDllNmQyNmQ0OGNiMmI5MTYxMzIzZGYzODNhMjJlNTI1NmNkZGJhOWU4YzIyNmVkY2NmOTY5MjBmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YRADF93gs66SqU_ZB3Y5kqkz2V_f6vYwIzf0F4M33aQ)

Let's add that to the issue https://github.com/freeats/freeats/issues/174
