### ISSUE TITLE
Fix reply toggle placement in notes

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#182]
**How it works**
After you leave a reply note, reply toggle placement is broken:

![CleanShot 15 11 2024 at 00-56](https://github.com/user-attachments/assets/fe779cb1-3a7a-45ce-861a-5c09e7c8c13a)

**How it should work**
Reply toggle should be in the same place as for already existing reply note:

![CleanShot 15 11 2024 at 00-57](https://github.com/user-attachments/assets/87db5d56-c0ba-4500-afed-afef76fdd8fb)

**Comment by ksnitsky** [comment]
Duplicated https://github.com/freeats/freeats/issues/150
