### ISSUE TITLE
Fix pagination styles

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#198]
**Problem**
On grid pages:
- we add `disabled` class for currently opened page, unlike in Tabler
- there is border at the right end, unlike in Tabler

![CleanShot 15 11 2024 at 15-18](https://github.com/user-attachments/assets/7674b13c-38ea-4f26-a344-76364c18378b)

[Tabler](https://preview.tabler.io/pagination.html#):

![CleanShot 15 11 2024 at 15-19](https://github.com/user-attachments/assets/4fbbfdc6-c223-4e01-b5a0-733b34ad312f)

**Solution**
- remove border at the right end
- add styles for active link as in Tabler, but keep it disabled so that user will not be able to reload page, focus it via tab, etc.

**Comment by ksnitsky** [comment]
> add styles for active link as in Tabler, but keep it disabled so that user will not be able to reload page, focus it via tab, etc.

But the current `disabled` still allows you to select a button via tab (any button, not just pagination)
A simple option is to do as it works now (disable pointer events). Hardly anyone clicks these buttons via tab anyway

**Comment by amgalanbadmaev** [comment]
Ok, please create separate issue to disable focusing via Tab and add label expert if it will take more than 1h (also please mention this issue in description).

**Comment by amgalanbadmaev** [comment]
@ksnitsky please create separate issue to disable focusing via Tab and add label expert if it will take more than 1h (also please mention this issue in description).
