### ISSUE TITLE
Fix search placeholder in navbar

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#211]
**How it works**
On big resolutions (>Small breakpoint) overflow:ellipsis is applied when there is enough space to fit whole placeholder text. On click "Press S" placeholder appears and only after you clicked in any other place whole placeholder text "Press S to search" appears.

![image](https://github.com/user-attachments/assets/8a7e9c60-7953-4d19-91cf-abea248bc344)

![image](https://github.com/user-attachments/assets/e3337411-fc4e-42ab-a901-323b5bd4da09)

Related PR: https://github.com/freeats/freeats/pull/205

**How it should work**
Whole placeholder text should be visible when there is enough space in select to fit the text.

**Comment by olegp** [comment]
This does not seem to be related to breakpoints. Instead I see the text change after a while as I navigate around the site at any resolution.
