### ISSUE TITLE
Career site fixes: Position page - Application form validation

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#22]
**Problem**
On Career site, Position page, for Application form:

- We show validation via browser tooltip (i.e. "Please fill out this field"), while initially planned to use [bootstrap styles](https://getbootstrap.com/docs/5.3/forms/validation/#custom-styles) (as in Hub on Change password page)

**Solution**
- Try to switch to [bootstrap styles](https://getbootstrap.com/docs/5.3/forms/validation/#custom-styles) for validation (problem is that bootstrap uses js to intercept browser validation and show own instead, so we need to test that validation will look correct in case js isn't loaded)

**Comment by amgalanbadmaev** [comment]
Note to myself: 
 --tblr-form-valid-color: #2fb344;
  --tblr-form-valid-border-color: #2fb344;
  --tblr-form-invalid-color: #d63939;
  --tblr-form-invalid-border-color: #d63939;

icon color matches border-color
