### ISSUE TITLE
Fix buttons placement on Settings for low resolutions

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#227]
**How it works**
On Settings page, on 320px width viewport button "Delete" doesn't fit within container:

![CleanShot 19 11 2024 at 15-02](https://github.com/user-attachments/assets/ff05e0ee-2c17-4815-9070-e160d1c1f9d4)

**How it should work**
On small breakpoints (Small, Extra small) place Upload and Delete buttons below avatar, keep 8px spacing between them.

**Comment by Lyams** [comment]
> On small breakpoints (Small, Extra small) place Upload and Delete buttons below avatar, keep 8px spacing between them.

@amgalanbadmaev  Place buttons in one line below the avatar on low resolutions? Or in two lines?

**Comment by ksnitsky** [comment]
> On small breakpoints (Small, Extra small) place Upload and Delete buttons below avatar, keep 8px spacing between them.

Means less than 768px (md) or less than 576px (sm)?

Because from what I've read it looks like `< md` and then it looks like this at ~750px:

![image](https://github.com/user-attachments/assets/0b5446a8-56fa-494c-a475-47eab23436dc)

**Comment by amgalanbadmaev** [comment]
Means less than 768px
