### ISSUE TITLE
Fix text overlapping with chevron in selects

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#238]
**Problem**
In Select text ignores chevron and overlaps with it:

![CleanShot 20 11 2024 at 11-18](https://github.com/user-attachments/assets/dc189c08-898e-485a-9ea0-bcf2c2224aa0)

**Solution**
In Bootstrap this is solved via increased right-padding (to cover up chevron space):

![CleanShot 20 11 2024 at 11-20](https://github.com/user-attachments/assets/5f88ca9b-64fd-4fbc-bc62-d9800ee1cd60)

Try to use similar approach. If our chevron sizes changes depending on select's size (Medium, Small, Tiny), set different right-padding, so that we don't occupy extra space for it.

Note that both placeholder, selected values texts shouldn't overlap with chevron and should be truncated when don't fit within select.

Should be done after we replace default triangles with chevron.

**Comment by amgalanbadmaev** [comment]
If you select option with long text, text overlaps with chevron:

![CleanShot 21 11 2024 at 17-27](https://github.com/user-attachments/assets/cf31115d-7e2d-4de1-9515-b267a76f3476)

Or change resolution:

![CleanShot 21 11 2024 at 17-29](https://github.com/user-attachments/assets/205baf24-bcab-48ca-b14c-d8afb06692a3)

How did we set paddings? I see that number are XX.XXX (3 digits after `.`)

**Comment by wrmk** [comment]
will look
right padding is: 8px + chevron_width * 1.41
1.41 is necessary because we rorate chevron on 45deg

**Comment by wrmk** [comment]
seems we removed some part of the truncation logic when adapting tabler, because in the internal project it truncates fine.
looking into

**Comment by wrmk** [comment]
my bad, forgot to copy another one style

**Comment by amgalanbadmaev** [comment]
Could we please normalize right-paddings to:
- Medium: 24px
- Small: 18px
- Tiny: 15px

And also change chevron color to tblr-gray-500

**Comment by wrmk** [comment]
though, padding also will fix there too
