### ISSUE TITLE
Career site fixes: Position page

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#24]
**Problem**
On Career site, Position page:

- Heading: incorrect font-size 20px
- Application form section:
  - Outdated heading text “Apply for this job”
  - Incorrect inputs size - Small
  - Button stretched to full-width on all resolutions

**Solution**
- Heading: increase font-size from 20px to 24px (shouldn’t be applied for Application form)
- Application form section:
  - Change heading from “Apply for this job” to “Apply for this position”
  - Change inputs size to Medium
  - Button should be stretched to full-width only on low resolutions (Small, Extra small breakpoints)

**Comment by Lyams** [comment]
> * Investigate why inputs Name and Email have incorrect height due to line-height 22.8571px (should be 40px height, as in File input below - set line-height to 1.5x)
> 
> ![CleanShot 14 11 2024 at 19-29](https://private-user-images.githubusercontent.com/98384586/386282588-c86853e1-01b2-4b57-b336-1918ced90634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE0NjQsIm5iZiI6MTczMjAwMTE2NCwicGF0aCI6Ii85ODM4NDU4Ni8zODYyODI1ODgtYzg2ODUzZTEtMDFiMi00YjU3LWIzMzYtMTkxOGNlZDkwNjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwOTNkMWVjY2VhNzQ4Y2ZkYzY3YzVmMDg4MTVmNGUzNmZlMTM5YjM2MTg5ZmEzNzFhNTNiYjJmYzA1N2E2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KgAaxwMh104MAbSK8VhKT8ZnImajhe_xJZpIODp9so4)
> 
> * Set font-size in File input to be 16px with 24px line-height (1.5x), as in inputs above
> * Submit button stretched to full-width on all resolutions, should be stretched to full-width only on low resolutions (Small, Extra small breakpoints)
> 
> Examples for Submit button:
> 
> ![CleanShot 14 11 2024 at 19-31](https://private-user-images.githubusercontent.com/98384586/386283184-08ecc61a-2f7e-40ba-9d9b-49de78e6d764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE0NjQsIm5iZiI6MTczMjAwMTE2NCwicGF0aCI6Ii85ODM4NDU4Ni8zODYyODMxODQtMDhlY2M2MWEtMmY3ZS00MGJhLTlkOWItNDlkZTc4ZTZkNzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OGNmMGUxMjMyYzQ2NmExM2VlYjg4Y2RjNWMxMTg1YTQ3NzUzZmMxNmRiZmNiNGYyNWIwZjYwNzcwMWYwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KN5kpCN3l29WXHtVkbNyXT4bvcQ5daI8_gcgm-juZ74)
> 
> ![CleanShot 14 11 2024 at 19-32](https://private-user-images.githubusercontent.com/98384586/386283368-e28c871d-676e-4dc2-b681-340321fd56ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDE0NjQsIm5iZiI6MTczMjAwMTE2NCwicGF0aCI6Ii85ODM4NDU4Ni8zODYyODMzNjgtZTI4Yzg3MWQtNjc2ZS00ZGMyLWI2ODEtMzQwMzIxZmQ1NmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OTI2ZDU5MjM4NTM2NDUwMjBjOTMxYzBjNTJmOTE0OWJlNzFlZTZlZDg2YTBmZDhiMmNhNWVhZThjYzIzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.THZ8iXhUcjkoD9z1QcnoGBcwOytMSKkPnD9TfK-JYg8)

@ksnitsky I'm having trouble deciding. Could you look into this issue?
