### ISSUE TITLE
Prepare a container for the administration interface and move the profile's settings into there

### ISSUE THREAD

**Issue by wrmk** [freeats/freeats#254]
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1720-10529&t=Aivif5wlJq7UHGM0-1)

- [x] Container:
  - [x] Use Tabler’s [Settings](https://preview.tabler.io/settings.html) container and layout
  - [x] Keep our page container paddings (24px top&side, 48px bottom)
  - [x] Use our H1 for page heading (24px font-size, 32px line-height)
  - [x] By default page content should occupy half of the space on md breakpoint and larger
  - [x] Remove footer with buttons, instead place “Save” button below page content
    - No need for “Cancel” button
    - On success display full-width success alert above container with text “All changes have been saved.”
- [x] In user’s avatar dropdown menu, on clicking “Settings” option redirect to this interface on “Profile” page (see below)
- [x] For admins set links in navigation sidebar to this:
  - [x] Personal (title)
    - Profile
  - [x] Company (title)
    - General
  - [x] Recruitment (title)
    - Sources
    - Disqualify reasons
- [x] For members set links in navigation sidebar to this:
  - [x] Personal (title)
    - Profile
- [x] On mobile:
  - [x] Replace Tabler’s navigation sidebar with our tab button dropdown; If it takes 4 hours or more to implement or requires hacks, keep Tabler's version.
  - [x] Nice-to-have: if implemented as tab button dropdown, in dropdown menu add dropdown headers (for titles, add icons too) as in [Tabler](https://preview.tabler.io/dropdowns.html)
- [x] Add icons for titles in navigation sidebar:
  - [x] Personal: [user](https://tabler.io/icons/icon/user) (15x15px, outline,  stroke width 1.25, gray-500 color)
  - [x] Company: [building](https://tabler.io/icons/icon/building) (15x15px, outline, stroke width 1.25, gray-500 color)
  - [x] Recruitment: [search](https://tabler.io/icons/icon/search) (15x15px, outline, stroke width 1.25, gray-500 color)
- [x] Profile page
  - [x] Route: /settings/personal/profile
  - [x] Title: Settings - Personal - Profile | FreeATS
  - [x] Copy all content from “Settings” page
    - [x] Use tabler’s default font-weight for labels - 500
    - [x] Change heading to “Profile”
    - [x] Add “Enter full name” placeholder for Full name input
    - [x] Add “Password” label before “Change password” link
    - [x] Remove full-width param for “Save” button
    - [x] Set spacing as on mockup
  - [x] Remove “Settings” page
  - [x] Avatar upload, deletion and linking email should apply effect without need to press “Save” button as currently implemented

**Comment by amgalanbadmaev** [comment]
Yes, please use 500

![CleanShot 27 11 2024 at 10-28](https://github.com/user-attachments/assets/6fb6d96d-9406-49e5-93e5-4b4fb3f6d3ca)
