### ISSUE TITLE
Add general company page in settings

### ISSUE THREAD

**Issue by Lyams** [freeats/freeats#266]
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1720-10529&t=Aivif5wlJq7UHGM0-1)

**General page:**
- [x] Route: /settings/company/general
- [x] Title: Settings - Company - General | FreeATS
- [x] Heading “General”
- [x] Add “Company name” field
- [x] Label: Company name
- [x] Placeholder: Enter company name

**No-gos**
Do not implement company logo picture upload and deletion, on mockup is for future

**Comment by wrmk** [comment]
@amgalanbadmaev please clarify what text for success notice should be on pressing the save button?
rn is "Company successfully updated."

and please clarify, should we display the building icon in a place where we will allow to upload the logo in the future?
![image](https://github.com/user-attachments/assets/6f0f5fd7-44d8-4d9e-9630-797815495bd2)
