### ISSUE TITLE
Add Sources page in settings

### ISSUE THREAD

**Issue by Lyams** [freeats/freeats#271]
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1720-10529&t=Aivif5wlJq7UHGM0-1)

- [x] Route: /settings/recruitment/sources
- [x] Title: Settings - Recruitment - Sources | FreeATS
- [x] Heading “Sources”
- [x] Allows Admins to customize Candidate's Source field options in Contact info card
- [x] Text input with delete icon-button, placeholder "Source"
- [x] Sources should be fully deleted:
  - [x] Full delete source only after user clicked “Save” button
  - [x] If there is at least one source deleted, on clicking “Save” button show modal dialog (see below)
- [x] Display in alphabetical order, reorder after “Save” button is pressed
- [x] “LinkedIn” source should be in readonly state and delete icon-button hidden; add it on creating tenant; always at the top

Delete modal for source:
- [ ] Title: Delete source/sources?
- [x] Body: Source/sources SOURCE1, SOURCE2 will be permanently removed from any candidates that have it set.
- [x] Buttons: Cancel, Delete

**Comment by wrmk** [comment]
@amgalanbadmaev please clarify should we create event for candidate about removed source when delete source in settings interface?

**Comment by Lyams** [comment]
> please clarify should we create event for candidate about removed source when delete source in settings interface?

If the answer is yes, then who should be listed in the activity as the actor - FreeATS or the admin who deleted the source?

**Comment by wrmk** [comment]
need to discuss via call

**Comment by delavaler** [comment]
Let's create event for all candidates about removing source, actor user -- user who deleted source in rails admin.

No-go: move the process to job, do this only if removing source process became too slow

**Comment by Lyams** [comment]
@amgalanbadmaev @delavaler If a user changes two sources to the same name, should we show an error? If not, what is the procedure?

**Comment by amgalanbadmaev** [comment]
Can we add uniq validation for both Source name and Disqualify reason name?

**Comment by delavaler** [comment]
> Can we add uniq validation for both Source name and Disqualify reason name?

yes, they should be uniq per tenant

**Comment by wrmk** [comment]
@amgalanbadmaev please clarify
is this scenario ok for us?
 - we delete any source which is used for any candidate
 - we press save and appears the confirmation modal about deleting source
 - we press cancel button in modal and almost deleted sources do not appear in the sources list until we reload the page

**Comment by amgalanbadmaev** [comment]
Decided to keep current scenario; Reason: will have to add logic for Dismiss ("X") button in modal too, better to wait for feedback from users.
