### ISSUE TITLE
Career site fixes: Footer

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#28]
**Problem**
On Career site, Positions list page:
- Footer have extra 16px spacing for the bottom part

![CleanShot 31 10 2024 at 14-42](https://github.com/user-attachments/assets/e4ada04c-5f13-4892-99a6-d18c1e2221bd)

On Career site, Position page:
- Similar issue

**Solution**
Remove extra 16px spacing at the bottom of footer.

**Comment by Lyams** [comment]
Fixed in https://github.com/freeats/freeats/issues/38

**Comment by amgalanbadmaev** [comment]
Let's remove fixed height for footer on large breakpoints.

**Comment by amgalanbadmaev** [comment]
On [Positions list page](https://app.freeats.com/sites/tough): there is blank space below footer (only applicable for Desktop version)

![CleanShot 19 11 2024 at 10-56](https://github.com/user-attachments/assets/14dbd022-baed-44ef-a1b8-61d8e854e660)

On [Position page](https://app.freeats.com/sites/tough/positions/business-developer-39): everything is correct, no blank space.

![CleanShot 19 11 2024 at 10-57](https://github.com/user-attachments/assets/1e44705f-e19e-476a-8eba-f67ba7f3d43f)

Can this be fixed? @Lyams @ksnitsky

**Comment by Lyams** [comment]
> Can this be fixed? @Lyams @ksnitsky
> Let's remove fixed height for footer on large breakpoints.

@amgalanbadmaev  Looks like we still need a minimum footer height

**Comment by Lyams** [comment]
> > Can this be fixed? @Lyams @ksnitsky
> > Let's remove fixed height for footer on large breakpoints.
> 
> @amgalanbadmaev Looks like we still need a minimum footer height

Probably Konstantin suggested me a different approach.
