### ISSUE TITLE
Change label for add-on in file input

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#280]
**Problem**
On Career site, Position page: Add-on have default label "Choose File":

![CleanShot 29 11 2024 at 23-46](https://github.com/user-attachments/assets/f4f9b2a7-889b-4562-955a-acd9c13a378c)

**Solution**
Change label to "Upload CV" as on [mockup](https://www.figma.com/design/Y5QG2xnRsnyB65EHiCxyho/Production-%5BATS%5D?node-id=2678-37523&t=Goee5iSEmLIuKcH6-1).

**Rabbit holes**
Don't use js, try to make it with css, if impossible, close issue as won't fix

**Comment by ksnitsky** [comment]
I was wrong, it can't be done without JS
