### ISSUE TITLE
fix styles for email compose

### ISSUE THREAD

**Issue by wrmk** [freeats/freeats#291]
- [x] For “New message” text change font-size to 16px and font-weight to 500 as in other cards
- [x] For “To:”/”Cc:”/”Bcc:” text change color to tblr-gray-800
- [x] For text area: change placeholder text color to tblr-gray-400
- [x] For container
  - [x] Change spacing (paddings) to be as in [mockup](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=2135-4743&node-type=canvas&t=cQKTlFHB4AD4iaS2-0)
- [x] For “Send” button: change size from Tiny to Small (32px)
- [x] Nice-to-have: For Cc/Bcc list email options in alphabetical order

**Comment by amgalanbadmaev** [comment]
- [ ] In div with Send button: change side paddings from 16px to 20px
- [ ] In Cc, Bcc buttons: change line-height from 16px to 18px (as in other Tiny buttons)
