### ISSUE TITLE
Candidate photos are not added when first adding them via the extension

### ISSUE THREAD

**Issue by olegp** [freeats/freeats#298]
**How it works**

Add any candidate and the photo is not visible, even after waiting for a bit and reloading the page. When you add the same candidate a second time, the photo appears immediately.

**How it should work**

The photo should appear after adding a candidate the first time.

**Comment by olegp** [comment]
@wrmk The photo is now added fine, however I also see the alert "Reload the page and try again" on the profile page. The profile is imported correctly without having to click the extension button another time. Can you reproduce? Is this related? If so, please reopen and fix. If not, please create a new issue.

**Comment by wrmk** [comment]
I can't reproduce this alert for the freeats helper (and for helper for the internal project too)
also this message "Reload the page and try again" is used only in the internal project.

are you sure that you see an alert with this message when using freeats helper?

**Comment by olegp** [comment]
I couldn't reproduce this now either, was likely some weird interaction between different extensions.
