### ISSUE TITLE
Update navbar styles

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#30]
**Problem**
Our current navbar doesn't match the one Tabler's provide:

![CleanShot 02 11 2024 at 10-00](https://github.com/user-attachments/assets/cd79b0ee-123c-4a79-942b-fde535350f29)

**Solution**
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1442-15593&t=YeWiWPdiI26dmnnH-1)

Let's update our navbar styles to match the one in Tabler:
- Desktop:
  - [x] Keep 24px side paddings (to match paddings in page layout)
  - [x] Keep our 1.5 line-height for text
  - [x] Change badge placement according to the mockup (centered, 4px spacing between text and badge)
  - [x] Set spacing between search input and avatar to 16px
- Mobile:
  - [x] Keep 24px side paddings (to match paddings in page layout)
  - [x] Set 16px spacing between elements
  - [x] When opened: highlight currently opened page with `--tblr-primary` color (#066FD1)
  - [x] Do not trigger sub-menu when avatar is clicked, instead display "Settings" and "Sign out" options in main menu below separator line

**Comment by wrmk** [comment]
seems "Keep 24px side paddings" already was fixed

**Comment by wrmk** [comment]
@amgalanbadmaev "Change badge placement" means badge for tasks tab?
![image](https://github.com/user-attachments/assets/578356b5-50f9-4b35-9ed4-c5b9cafa7737)

**Comment by wrmk** [comment]
do we want to fix this jumping?

https://github.com/user-attachments/assets/3bcc24c2-438f-4bae-96df-92daaa039f91

**Comment by wrmk** [comment]
we did not highlight opened nav in desktop
our
![image](https://github.com/user-attachments/assets/7c22789b-f026-4fe0-9b70-9f61ad8d05aa)

 mockup
![image](https://github.com/user-attachments/assets/957dbe55-e0e6-4d2f-80a1-37b01bcd747e)

**Comment by wrmk** [comment]
do we want to fix this in this issue?
"Settings" and "Sign out" looks strange

![image](https://github.com/user-attachments/assets/89508308-9226-4911-a2bd-9bd478c2313d)
![image](https://github.com/user-attachments/assets/86551a96-0ddc-4967-9883-f906f9812039)

**Comment by amgalanbadmaev** [comment]
> * "Keep 24px side paddings" already fixed
> * " Keep our 1.5 line-height for text" already fixed

this was added since Tabler's navbar have different paddings and line-height set

**Comment by amgalanbadmaev** [comment]
> @amgalanbadmaev "Change badge placement" means badge for tasks nav? ![image](https://private-user-images.githubusercontent.com/31632314/383817803-578356b5-50f9-4b35-9ed4-c5b9cafa7737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjU1OTgsIm5iZiI6MTczMDk2NTI5OCwicGF0aCI6Ii8zMTYzMjMxNC8zODM4MTc4MDMtNTc4MzU2YjUtNTBmOS00YjM1LTllZDQtYzViOWNhZmE3NzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZDEyYTRlYmFjYzlmYzgxZDkxMDIzYjU1YTcwNzI0MDZmYWI5MDc5NjMzODM4MjhlZTVkMjJlZTkzNDE2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RSN-4yLg6aWciLaXUYGvfwmCjOaNFdUu9MjjKIRlhBs)

yes, should be as on mockup

![CleanShot 07 11 2024 at 11-56](https://github.com/user-attachments/assets/1097c251-61cc-44c3-b131-2293aee0f4c9)

**Comment by amgalanbadmaev** [comment]
> before adapt the search field we have to do this [issue](https://github.com/freeats/freeats/issues/40) because rn chevron down displays for all select fields ![image](https://private-user-images.githubusercontent.com/31632314/383823280-e4c8a58f-b39a-44ae-891b-65d1bea6615e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAxMjEsIm5iZiI6MTczMDk2OTgyMSwicGF0aCI6Ii8zMTYzMjMxNC8zODM4MjMyODAtZTRjOGE1OGYtYjM5YS00NGFlLTg5MWItNjVkMWJlYTY2MTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjIxZmViMTliYTlhNDRkOWM1M2I2ZTZjMTY3MTY0NGM1NzI0N2IyMGVjMGVkNzM4OWUyZDI0OWZlODRiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5jilp1l5wEySaafn5ozb1joT252t2ob7MI0tt8qCOuE)

Should we close this issue and create separate to set styles for Navbar after the mentioned issue for select @delavaler ?

**Comment by amgalanbadmaev** [comment]
> do we want to fix this in this issue? "Settings" and "Sign out" looks strange
> 
> ![image](https://private-user-images.githubusercontent.com/31632314/383870459-89508308-9226-4911-a2bd-9bd478c2313d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njc1OTYsIm5iZiI6MTczMDk2NzI5NiwicGF0aCI6Ii8zMTYzMjMxNC8zODM4NzA0NTktODk1MDgzMDgtOTIyNi00OTExLWEyYmQtOWJkNDc4YzIzMTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4MTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNjAzYmVjOGNmZTM5ZmE4YmRhMWYyZWU1MGIzNTlmOGI0NjU3YTkyMTFjNDBiYWNiNDMwMTI4ZmRjZmJjYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l6KAwqhjM4zMaiISz617uZdm0UO0s6b6pCJZ1a-RKvY) ![image](https://private-user-images.githubusercontent.com/31632314/383870673-86551a96-0ddc-4967-9883-f906f9812039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njc1OTYsIm5iZiI6MTczMDk2NzI5NiwicGF0aCI6Ii8zMTYzMjMxNC8zODM4NzA2NzMtODY1NTFhOTYtMGRkYy00OTY3LTk4ODMtZjkwNmY5ODEyMDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4MTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOTgyMGE2YTAzYTY0MGE3ZGEyNzUxNDc2Yjg0YzY5MjZlNWI0NjczNGE4MGE4MDUzMmNhYjY5ZmFiNzg1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fTHWavYLMsv9bTapILWGDR9QPyRLfFfXkLJBvA1wFDo)

Yes, please fix. Note that currently opened page should also be highlighted via tblr-primary color for nav-link text on Mobile.

**Comment by amgalanbadmaev** [comment]
Also separator line on mobile navbar menu currently is not visible due to white color. Should be changed to #DCE1E7 (or the one tabler uses in their own).

**Comment by wrmk** [comment]
> Yes, please fix. Note that currently opened page should also be highlighted via tblr-primary color for nav-link text on Mobile.

should we colorize "Settings" on desktop?
do not look at ugly dropdown, will fix it
![image](https://github.com/user-attachments/assets/799eba31-d4f9-49f1-974c-5b5efee59b71)
![image](https://github.com/user-attachments/assets/4a842513-4fb3-4989-a982-ea7ab7b1d1c0)

**Comment by amgalanbadmaev** [comment]
No, only on mobile please

**Comment by delavaler** [comment]
> > before adapt the search field we have to do this [issue](https://github.com/freeats/freeats/issues/40) because rn chevron down displays for all select fields ![image](https://private-user-images.githubusercontent.com/31632314/383823280-e4c8a58f-b39a-44ae-891b-65d1bea6615e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAxMjEsIm5iZiI6MTczMDk2OTgyMSwicGF0aCI6Ii8zMTYzMjMxNC8zODM4MjMyODAtZTRjOGE1OGYtYjM5YS00NGFlLTg5MWItNjVkMWJlYTY2MTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjIxZmViMTliYTlhNDRkOWM1M2I2ZTZjMTY3MTY0NGM1NzI0N2IyMGVjMGVkNzM4OWUyZDI0OWZlODRiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5jilp1l5wEySaafn5ozb1joT252t2ob7MI0tt8qCOuE)
> 
> Should we close this issue once all other things are done and create separate to set styles for Navbar after the mentioned issue for select @delavaler ?

sounds reasonable

**Comment by wrmk** [comment]
not quite understand, close the whole issue or just part with the search field. I almost made other fixes.

**Comment by wrmk** [comment]
is this behaviour ok for us? (doubled options when open 2 dropdowns)

https://github.com/user-attachments/assets/f9d66244-81cf-4d17-bee3-7cbde2ce1d87

**Comment by amgalanbadmaev** [comment]
> not quite understand, close the whole issue or just part with the search field. I almost made other fixes.

ignore Search input (icon and kbd text) points in issue, will be moved to separate one

**Comment by amgalanbadmaev** [comment]
> is this behaviour ok for us? (doubled options when open 2 dropdowns)
> 
>  simplescreenrecorder-2024-11-08_09.27.59.mp4

can we make so that on mobile Avatar doesn't open dropdown menu at all?

**Comment by wrmk** [comment]
but i think we should make nav after clicking on avatar on mobile
"Do not trigger sub-menu when avatar is clicked, instead display "Settings" and "Sign out" options in main menu below separator line" - please clarify what do we need here

**Comment by amgalanbadmaev** [comment]
But keep in mind that on Desktop it should open (since we don't display these links in navbar)

**Comment by amgalanbadmaev** [comment]
On 320px viewport avatar wraps to the 2nd row, Tabler's navbar doesn't have this issue:

![CleanShot 13 11 2024 at 14-25](https://github.com/user-attachments/assets/f5902c02-cc95-4b89-aba0-8de8adee065e)

![CleanShot 13 11 2024 at 14-26](https://github.com/user-attachments/assets/c3c477ab-b1a3-4366-97e0-1af0c86b8ee7)

**Comment by wrmk** [comment]
i think tabler has the same problem too
![image](https://github.com/user-attachments/assets/767ec297-4d01-47d9-bbf5-a1628684ce34)

seems in our case the select field wants more space, we may try to fix this

**Comment by amgalanbadmaev** [comment]
Let's do it
