### ISSUE TITLE
js(selectize deps): add tabler icons as default into selectize fork

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#35]
related with #129

**Problem**
Adding a tabler icon in selectize proved difficult, so the chevron and check icons were removed
![image1](https://github.com/user-attachments/assets/a1c8ff66-62c8-484b-9d2f-1b83ddb197b3)
![image2](https://github.com/user-attachments/assets/5d0c6cae-7e1a-4933-bb82-cf39b920a39b)

**Solution**
Add these icons to [our selectize fork](https://github.com/toughbyte/selectize.js) and use them there. check icon in `deselect_options_via_dropdown` plugin, and chevron in the field itself instead of the standard arrow if it was initialized with `showArrow: true` parameter

**Comment by ksnitsky** [comment]
Spent 2 hours, webfont doesn't work

**Comment by wrmk** [comment]
agreed to compose icons by borders in `::after` element
