### ISSUE TITLE
Fix watched checkbox on tasks page

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#36]
It should be centered

**Comment by ksnitsky** [comment]
Still relevant?
![image](https://github.com/user-attachments/assets/4451a600-100d-4c30-8581-0f36fc278cec)

**Comment by delavaler** [comment]
> Still relevant? ![image](https://private-user-images.githubusercontent.com/41356747/385302089-4451a600-100d-4c30-8581-0f36fc278cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjIxMTIsIm5iZiI6MTczMTQyMTgxMiwicGF0aCI6Ii80MTM1Njc0Ny8zODUzMDIwODktNDQ1MWE2MDAtMTAwZC00YzMwLTg1ODEtMGYzNmZjMjc4Y2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0MzAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOGNmZTRiYTA4NjE3MDNhYTg1MTgyODRkY2Q4ODM4YWQxNGEzYmZlOGZhZDliMDNmNGFkNjJhNjJhYzI0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.inAwHLgw46MjHl3Ijg3PclRQhWQVzRyppq6paFJ6EQM)

@amgalanbadmaev  could you check please?

**Comment by amgalanbadmaev** [comment]
Yes, off center relative to the row

![CleanShot 12 11 2024 at 17-42](https://github.com/user-attachments/assets/92f6ba90-5c1f-404a-870d-d26b83e215d6)
