### ISSUE TITLE
Update dashboard typography

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#37]
Dashboard page: “Your positions” and “Your candidates” font-size and line-height shouldn’t be changed

**Comment by ksnitsky** [comment]
What about font-weight?
tabler fw-bold is 600, bootstrap 700

**Comment by ksnitsky** [comment]
The old line-height: 1.2 (24px), and the default in tabler for h2 (matching the font size with the old one) is 1.75rem (28px)
Which one should I set?

**Comment by delavaler** [comment]
@ksnitsky  could you please mention @amgalanbadmaev  to clarify all design related issues?

**Comment by amgalanbadmaev** [comment]
Let's set:
- font-weight 600
- line-height 24px
