### ISSUE TITLE
js: show selectize arrow only for local select component

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#40]
**Problem**
During the adaptation of tabler icons there were difficulties with replacing fontawesome chevron icon with tabler chevron icon, so it was decided to return the standard selectize arrow, but it came back for all select inputs, although it is needed only in `local` fields.

**Solution**
Add a condition to show this arrow

**Comment by wrmk** [comment]
there is a problem, multiple (and pill probably) components do not display an arrow from the box. 
looks like a bug in the selectize library

**Comment by wrmk** [comment]
though, [fixed](https://github.com/toughbyte/selectize.js/pull/23)
