### ISSUE TITLE
Fix tasks form elements

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#47]
- [x] margin becomes bigger on starting editing description
- [x] select inputs open after making changes (but it probably will be fixed on improving select components)

**Comment by wrmk** [comment]
what tasks' form elements we want to fix?
![image](https://github.com/user-attachments/assets/ebb9300a-7224-4f57-81a0-e3a77b89e97c)

**Comment by delavaler** [comment]
Looks like they were fixed during the previous changes, initially form elements were doubled and it was impossible to select watchers.
Right now I see the next issues:
1. margin becomes bigger on starting editing description
2. select inputs open after making changes (but it probably will be fixed on improving select components)
![Screenshot from 2024-11-07 10-08-38](https://github.com/user-attachments/assets/281cab71-63c8-4db6-b718-6bd6c36ccee0)
![Screenshot from 2024-11-07 10-08-23](https://github.com/user-attachments/assets/6aa5e0a3-9e7d-4503-8fcd-55aa049421bb)
@amgalanbadmaev  do you see other problems?

**Comment by wrmk** [comment]
updated issue description (summarized problems)

**Comment by amgalanbadmaev** [comment]
- first can't reproduce anymore
- second is not relevant as I discovered - it is not padding adding, but scrollbar appears (screenshot)

![CleanShot 14 11 2024 at 10-31](https://github.com/user-attachments/assets/62232a1d-a221-4285-9f63-8347f062b40a)

**Comment by wrmk** [comment]
i'd like to merge other changes

**Comment by wrmk** [comment]
updated issue description
