### ISSUE TITLE
Change Cancel button style on modal to be like in Tabler

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#49]

**Comment by amgalanbadmaev** [comment]
Investigate why on hover we change text color (also seems like border-color change doesn't match the one in Lookbook and Tabler too):

![CleanShot 06 11 2024 at 16-07](https://github.com/user-attachments/assets/2c9ac484-5999-44c0-8c42-cebeffeb3f60)

In Lookbook text color doesn't change:

![CleanShot 06 11 2024 at 16-06](https://github.com/user-attachments/assets/ea5da3ca-7543-4508-91a0-44881eb15e1b)

In Tabler preview also doesn't change:

![CleanShot 06 11 2024 at 16-08](https://github.com/user-attachments/assets/d754b77d-500b-4e56-bacb-5465b11de18c)

**Comment by ksnitsky** [comment]
Fixed in https://github.com/freeats/freeats/pull/93
