### ISSUE TITLE
Return style: .text-input-component-disabled

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#50]
It should help distinguish disabled and not disabled components

**Comment by Lyams** [comment]
I will do it

**Comment by Lyams** [comment]
This css class exists:
https://github.com/freeats/freeats/blob/50297be1fd68e3619425474340167bddf8ba0210/app/assets/stylesheets/src/shared/_components.scss#L41-L47

@delavaler Could you please clarify the issue where the component is not displayed correctly?
