### ISSUE TITLE
Set Back link to lead to the page from which it was opened

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#53]
Here (app/views/rodauth/reset_password_request.html.slim) Back button leads to the settings page, while it should to lead to the page from which was opened: either Settings or Sign in. If the fallback location lwasn't found, let's redirect to the Settings for logged in users and to sign in for not logged in.

**Comment by wrmk** [comment]
rails provide `url_for(:back` which composes this if can't detect the back path, is this ok for us?
or we have to replace it with settings or sign in page

![image](https://github.com/user-attachments/assets/5dcb597d-e581-4378-af54-4439892b2676)

**Comment by wrmk** [comment]
when we navigate via our pages it correctly set back as settings or sign it page

**Comment by wrmk** [comment]
discussed that this solution is fine
