### ISSUE TITLE
Adapt remaining selects with our select component

### ISSUE THREAD

**Issue by wrmk** [freeats/freeats#58]
The project has several places where we use (form|f)\.select| select_tag, we want to replace them with the select component.

cleanup project from bootstrap-select after all.

**Comment by amgalanbadmaev** [comment]
@wrmk do you think these problems relevant to the issue?

- Datepicker calendar doesn't close when other select is active:

![CleanShot 06 11 2024 at 16-13](https://github.com/user-attachments/assets/97a9277e-7699-4175-8036-0d7dddf25b1a)

- We didn't import Tabler's style for dropdown menus for selects, right?

![CleanShot 06 11 2024 at 16-15](https://github.com/user-attachments/assets/9d90772e-e33e-4c17-8a82-9ce07e356119)
