### ISSUE TITLE
Update scorecards button and icon colors

### ISSUE THREAD

**Issue by ksnitsky** [freeats/freeats#61]
**Problem**
After switching to tabler, the colors remained the same

**Solution**
[Mockup](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1283-6726&t=2SADNKfvpSkpYFeW-4)

Update the colors of the scores buttons:
- Irrelevant - background-color: red-500, border-color: red-500
- Might be irrelevant - background-color: red-300, border-color: red-500
- Good candidate - background-color: green-300, border-color: green-500
- Perfect candidate - background-color: green-500, border-color: green-500

This is how the buttons should look without the option selected:
![image](https://github.com/user-attachments/assets/ef75c0eb-9f61-4c1e-b70b-5eac8d8a63fb)

And this is the active state:
![image](https://github.com/user-attachments/assets/16dbe053-5199-46ec-93ca-af45a2a2684f)

---

[Mockup](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1171-3878&t=2SADNKfvpSkpYFeW-4)
And for the face icons in the show card:
- mood_sad - red-500
- mood_empty - red-300
- mood_smile - green-300
- mood_happy - green-500

---

Also please fix icon placement in Score buttons: icon should be above text
![image](https://github.com/user-attachments/assets/433e771a-6cee-4b68-8b49-dbe248ec938e)

**Comment by amgalanbadmaev** [comment]
Also please fix icon placement in Score buttons: icon should be above text

![CleanShot 05 11 2024 at 13-07](https://github.com/user-attachments/assets/ce88a9e8-7b46-4f1b-beb2-448b7d1b584a)

**Comment by ksnitsky** [comment]
@amgalanbadmaev what should the style of the selected option look like?
