### ISSUE TITLE
Fix avatar

### ISSUE THREAD

**Issue by delavaler** [freeats/freeats#7]
**Problem**
Candidate page: avatar might be too small? - class 2xl
Settings page: avatar is too big - class md

**Comment by amgalanbadmaev** [comment]
- Displaying blacklisted badge when candidate is not blacklisted and vice versa:

![CleanShot 06 11 2024 at 16-31](https://github.com/user-attachments/assets/f9cf2b31-0594-42fc-a968-87e5a4c740a5)

![CleanShot 06 11 2024 at 16-32](https://github.com/user-attachments/assets/35d567cd-3dcc-4429-8c99-c9273cbee3a4)

- Is it possible to use our custom avatar block (the one on pipeline card) on the Settings page too? md class in description was set from outdated Tabler's documentation (need 64x64px size)?
