### ISSUE TITLE
Fix Pipelines styles

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#72]
**Problem**
Current Pipeline columns looks bad:

![CleanShot 05 11 2024 at 13-06](https://github.com/user-attachments/assets/7a2fa29c-01b9-4cf1-8967-dc2568b10cf3)

**Solution**
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1442-6528&t=8OO6JZm6OtBkLOzn-1)

For Pipeline columns:
- Set #DCE1E7 border-color
- Set #FFFFFF background color
- Set default badge styles for each counter
- Try to apply Tabler's Buttons group style for Tab buttons (qualified/reserved/disqualified)

![CleanShot 05 11 2024 at 13-05](https://github.com/user-attachments/assets/4e31d975-cffe-4f4c-9726-c55ebfc3f2c3)

Related: https://github.com/freeats/freeats/issues/16

**Comment by ksnitsky** [comment]
> Set #DCE1E7 border-color

What do you think about using the standard color of the card borders? `rgba(4, 32, 69, 0.1)`

**Comment by amgalanbadmaev** [comment]
This is also one of default border colors:
> tblr-border-color: #dce1e7;

I'm still not sure why they have 2.

**Comment by amgalanbadmaev** [comment]
- Investigate why our on hover style for active and non-active Tab buttons style differs from the ones in Button group in https://tabler.io/admin-template/preview -> Form elements

![CleanShot 06 11 2024 at 15-55](https://github.com/user-attachments/assets/f8520674-e0fb-45d0-8fa5-dacda9baf966)

- Also seems like non-active Tab buttons have shadow, please remove it

**Comment by ksnitsky** [comment]
Fixed in https://github.com/freeats/freeats/pull/93
