### ISSUE TITLE
Fix label + value font-size issues

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#73]
**Problem**
- [x] On Cards: Pipeline (value: scorecard template); Contact info (values: email, phones, source)
- [x] On Task modal: labels for existing task differs from New task modal
- [x] On Candidate's Scorecard: values font-size is 12px, above Summary card (both View and Edit modes)
- [x] On Position's Scorecard template: values font-size is 12px, above Questions card

![CleanShot 07 11 2024 at 15-44](https://github.com/user-attachments/assets/6b354362-dc79-4247-812d-0ad862139d1a)

![CleanShot 07 11 2024 at 15-42](https://github.com/user-attachments/assets/936c621e-57c6-4ceb-8dc6-713d6244061c)

![CleanShot 05 11 2024 at 13-11](https://github.com/user-attachments/assets/0493dbfa-d655-483b-a0a3-a7be96241c30)

![CleanShot 05 11 2024 at 13-11](https://github.com/user-attachments/assets/93617865-908f-496a-9668-1a371d3020ba)

**Solution**
- Set font-size for value and labels to be 14px

Please also fix similar issues if you notice them.

Related: https://github.com/freeats/freeats/issues/8

**Comment by Lyams** [comment]
@amgalanbadmaev  All the listed cases on the main branch and in production now, the font size is 14 pixels as it seems to me.
Is the issue relevant?

**Comment by wrmk** [comment]
"On Task modal: labels for existing task differs from New task modal" seems already solved
![image](https://github.com/user-attachments/assets/58be616f-f324-473c-adfc-2efb965a92d9)
![image](https://github.com/user-attachments/assets/9a8ea86d-5ba8-48fb-af73-e60a2d40f2eb)
