### ISSUE TITLE
Fix input for Scorecard template

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#74]
**How it works**
On Position's Scorecard template page, after you add question and fill it, bg-color for input changes:

![CleanShot 05 11 2024 at 13-15](https://github.com/user-attachments/assets/084238e1-151c-4dcc-a7da-efc596288304)

**How it should work**
Background color of the input shouldn't change.

**Comment by ksnitsky** [comment]
Is this still relevant? I can't reproduce
![image](https://github.com/user-attachments/assets/9ee411c3-9ea9-4bb7-a38c-6192cc0c575b)

**Comment by amgalanbadmaev** [comment]
Found out that it is only reproducable if browser autofills the field (from browser tooltip). Shouldn't be changed.
