### ISSUE TITLE
Add ToS and Privacy Policy links

### ISSUE THREAD

**Issue by amgalanbadmaev** [freeats/freeats#99]
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1520-10620&t=FzaeBhLZJcG26UQA-1)

On Career site for footer:
- If TOS_LINK env var present, add link with text "Terms of Service"; on hover show underline as in Tabler's footer
- If PRIVACY_LINK env var present, add link with text "Privacy Policy"; on hover show underline as in Tabler's footer
- Remove underline for "Career site" link and make whole "Career site by FreeATS" text as link; on hover show underline as in Tabler's footer
- Set `·` symbol as separator between Terms of Service and Privacy Policy links; 8px spacing between all 3 texts
- On Desktop: place "Terms of Service" and "Privacy Policy" links on the right side
- On Mobile: place "Terms of Service" and "Privacy Policy" links below "Career site by FreeATS" link; 16px spacing between them

**Comment by delavaler** [comment]
@amgalanbadmaev  do we have a reason why Privacy Policy and Terms of Service have all letters capitalized?

**Comment by amgalanbadmaev** [comment]
> @amgalanbadmaev do we have a reason why Privacy Policy and Terms of Service have all letters capitalized?

As in Tabler

**Comment by amgalanbadmaev** [comment]
@Lyams please confirm that text is "Terms of Service" and not "Term of Service" - there was a mistake in issue description and mockups, now fixed.

**Comment by Lyams** [comment]
> @Lyams please confirm that text is "Terms of Service" and not "Term of Service" - there was a mistake in issue description and mockups, now fixed.

It is ok. Changes on the branch with tabler.

![Screenshot from 2024-11-14 11-56-44](https://github.com/user-attachments/assets/c783b569-4ee2-4fab-898f-732602b663d3)
